'use client';
import React, { useState } from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
import Head from 'next/head';
import { ThemeProvider } from '@/Context/theme';
import Navbar from '@/components/components/Navbar';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [themeMode, setTheme] = useState('light');
    const toggleTheme = () => {
        const newThemeMode = themeMode === 'light' ? 'dark' : 'light';
        setTheme(newThemeMode);
        document.querySelector('html')?.classList.remove('light', 'dark');
        document.querySelector('html')?.classList.add(newThemeMode);
    };

    return (
        <html lang="en">
            <Head>
            
                <title>Aeravat</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="stylesheet"
                    href={`https://fonts.googleapis.com/css2?family=Inter:wght@400;500&display=swap`}
                />
                
            </Head>
            <ThemeProvider value={{ themeMode, toggleTheme }}>
                <body className={`relative ${inter.className}`}>
                    <Toaster position="top-center" />
                    <Navbar />
                    {children}
                </body>
            </ThemeProvider>
        </html>
    );
}
